[package]
name = "mcmod-manager"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
reqwest = { version = "0.12.23" }
toml = { version = "0.9.7" }
