# Modlist used by yours truly :)

[defaults]
game_version = "1.21.5"
loader = "fabric"

[projects]
blazeandcaves-advancements-pack={defaults=true, loader="datapack"}
iris.defaults=true
sodium.defaults=true
lithium.defaults=true
distanthorizons.defaults=true
modmenu.defaults=true
fpsdisplay.defaults=true
faithful-32x={defaults=true, loader="minecraft"}

[optional-projects]
camps_castles_carriages.defaults=true
stellaris.defaults=true
