[defaults]
game_version = "1.21.5"
loader = "fabric"

[projects]
blazeandcaves-advancements-pack={defaults=true, loader="datapack"}
iris.defaults=true
sodium.defaults=true
lithium.defaults=true
distanthorizons.defaults=true
camps_castles_carriages.defaults=true
