name: Conventional Name

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
        description: The name to check for validity

jobs:
  check_name:
    name: Check Name
    runs-on: ubuntu-latest
    steps:
    - name: Check Name
      shell: python
      run: |
        if [[ "${{ inputs.name }}" =~ ^(chore|docs|feat|fix)!?: .*$ ]]; then
          echo "::error::Pull request title should follow conventional naming."
          echo "::notice::Allowed types are chore, docs, feat, and fix."
          exit 1
        fi
