name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cargo-lint:
    name: Cargo Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cargo Format
      run: cargo fmt --check
    - name: Cargo Clippy
      run: cargo clippy -- -Dwarnings
  cargo-build:
    name: Cargo Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cargo Build
      run: cargo build
    - name: Setup Directories
      run: |
        mkdir ~/.minecraft
    - name: Cargo Test
      run: cargo test
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cargo Build
      run: cargo build
    - name: Setup Directories
      run: |
        mkdir ~/.minecraft
    - name: Run Integration Test
      run: |
        cargo run -- examples/integration_test.toml -d downloads -i
    - name: Check Downloads
      shell: python
      run: |
        from pathlib import Path

        def check_count(path, count):
          globbed = list(path.glob("*"))
          if len(globbed) != count:
            raise ValueError("Expected {count} items, found {globbed!r}")
        
        def check_dir(path):
          check_count(path / "datapacks", 1)
          check_count(path / "mods", 2)
          check_count(path / "resourcepacks", 1)

        check_dir("downloads")
        check_dir("~/.minecraft")
