name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cargo-lint:
    name: Cargo Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cargo Format
      run: cargo fmt --check
    - name: Cargo Clippy
      run: cargo clippy -- -Dwarnings
  cargo-build:
    name: Cargo Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cargo Build
      run: cargo build
    - name: Setup Directories
      run: |
        mkdir ~/.minecraft
    - name: Cargo Test
      run: cargo test
    - name: Integration Tests
      run: |
        cargo run -- examples/integration_test.toml -d downloads -i
