name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cargo-lint:
    name: Cargo Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cargo Format
      run: cargo fmt --check
    - name: Cargo Clippy
      run: cargo clippy --check
  cargo-build:
    name: Cargo Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cargo Build
      run: cargo build
    - name: Cargo Test
      run: cargo test
