name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ruff-check:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Run Ruff
      run: |
        pip install .[dev]
        ruff format mcmod_manager --check
        ruff check mcmod_manager
