name: Pull Request Edit

on:
  pull_request:
    type: [opened, synchronize, edited, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conventional_name:
    uses: ./.github/workflows/conventional_name.yml
    with:
      name: ${{ github.events.pull_request.title }}
