name: Pull Request

on:
  pull_request:

env:
  RUST_BACKTRACE: '1'

jobs:
  conventional_name:
    uses: ./.github/workflows/conventional_name.yml
    inputs:
      name: github.event.title
  target:
    uses: ./.github/workflows/target.yml
