name: Integration Test

on:
  workflow_call:
    inputs:
      artifact:
        description: The name of the artifact to test.
        type: string
        required: true
      runs-on:
        description: The system to run the test on.
        type: string
        required: true
      dot_minecraft:
        description: The path to .minecraft
        type: string
        required: true

env:
  RUST_BACKTRACE: '1'

jobs:
  integration-test:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: actions/download-artifact@v7
      with:
        name: ${{ inputs.artifact }}
    - name: Extract Archive (tar)
      if: ${{ endsWith(inputs.artifact, '.tar.gz') }}
      run: tar -xzvf ${{ inputs.artifact }}
    - name: Extract Archive (zip)
      if: ${{ endsWith(inputs.artifact, '.zip') }}
      run: unzip ${{ inputs.artifact }} -d .
    - name: Setup .minecraft
      run: mkdir ${{ inputs.dot_minecraft }}
    - name: Run Integration Test
      run: mcmod examples/integration_test.toml
