name: Release

on:
  push:
    tags: ['v*']

jobs:
  cargo-lint:
    name: Cargo Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cargo Format
      run: cargo fmt --check
    - name: Cargo Clippy
      run: cargo clippy -- -D warnings -D clippy::pedantic
  cargo-test:
    name: Cargo Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Cargo Test
      run: cargo test --release
  cargo-build:
    name: Cargo Build
    runs-on: ubuntu-latest
    env:
      release-dir: mcmod_manager-${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v5
    - name: Cargo Build
      run: cargo build --release
    - uses: actions/upload-artifact@v6
      with:
        path: target/release/mcmod
    - name: Make Release Archive
      run: |
        mkdir ${{ env.release-dir }}
        cp target/release/mcmod ${{ env.release-dir }}
        cp README.md ${{ env.release-dir }}
        cp -r examples ${{ env.release-dir }}/examples
        tar cvf ${{ env.release-dir }}.tar ${{ env.release-dir }}
    - uses: softprops/action-gh-release@v2.5.0
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        files: ${{ env.release-dir }}.tar
